# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.1
cache:
  directories:
  - "$HOME/.julia"
matrix:
  fast_finish: true
notifications:
  email: false
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - xorg-dev
before_script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
  - julia --color=yes -e 'using Pkg; pkg"add https://github.com/Gnimuc/Nuklear.jl.git"'
