# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.3
matrix:
  allow_failures:
    - julia: nightly
    - os: windows
  fast_finish: true
notifications:
  email: false
dist: bionic
services:
  - xvfb
after_success:
  - if [[ "$TRAVIS_OS_NAME" == osx && "$TRAVIS_JULIA_VERSION" == 1.3 ]] ; then julia --project=. -e 'using Pkg;
                                                                                                     Pkg.add("Coverage");
                                                                                                     using Coverage;
                                                                                                     Codecov.submit(process_folder())' ; fi
